### ISSUE TITLE
Wireframes for search views.

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/blacklight-refuge#15]

**Comment by ghost** [comment]
![image_gallery_home](https://cloud.githubusercontent.com/assets/8903554/11543287/c7698de4-9909-11e5-9ea7-486ccce2206e.png)
![image_filter](https://cloud.githubusercontent.com/assets/8903554/11543293/cde04d7a-9909-11e5-986f-8716846dce13.png)
![image_individual](https://cloud.githubusercontent.com/assets/8903554/11543296/d299452e-9909-11e5-9005-ed66050f0890.png)
