### ISSUE TITLE
Paginate gallery images

### ISSUE THREAD

**Issue by crowesn** [jamesvanmil/blacklight-refuge#21]
Cool to use sunspot for this?

**Comment by jamesvanmil** [comment]
Sunspot just for pagination? Am I missing something?

**Comment by crowesn** [comment]
It’s already in the Gemfile? Asked because I wondered if we were keeping it.

## 

Sean Crowe
Electronic Resources Librarian

Electronic Resources Dept.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edumailto:sean.crowe@uc.edu
gchat: crowesn

On Nov 30, 2015, at 9:11 AM, James Van Mil <notifications@github.com<mailto:notifications@github.com>> wrote:

Sunspot just for pagination? Am I missing something?

**Comment by jamesvanmil** [comment]
I'm using Sunspot to manage the data for the record search

**Comment by crowesn** [comment]
It comes with pagination and faceting functionality - ok to use it?

## 

Sean Crowe
Electronic Resources Librarian

Electronic Resources Dept.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edumailto:sean.crowe@uc.edu
gchat: crowesn

On Nov 30, 2015, at 9:22 AM, James Van Mil <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm using Sunspot to manage the data for the record search

**Comment by jamesvanmil** [comment]
yeah - the objects don't need to be in Solr for that to work?

**Comment by crowesn** [comment]
They do have to be in solr.

## 

Sean Crowe
Electronic Resources Librarian

Electronic Resources Dept.
University of Cincinnati Libraries
PO Box 210033
Cincinnati OH 45221-0033
Tel: (513) 556-1899
Fax: (513) 556-4393
Email: sean.crowe@uc.edumailto:sean.crowe@uc.edu
gchat: crowesn

On Nov 30, 2015, at 9:26 AM, James Van Mil <notifications@github.com<mailto:notifications@github.com>> wrote:

yeah - the objects don't need to be in Solr for that to work?
